[project]
name = "30-09-av5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pymysql>=1.2.3",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.1.1",
]

[project.scripts]
30-09-av5 = "30_09_av5:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
