[project]
name = "av5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "emilykraftmk11-creator", email = "emilykraftmk11@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pymysql>=1.2.3",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.1.1",
]

[project.scripts]
av5 = "av5:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
