[project]
name = "meuprojeto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vinicius-vwa", email = "altoffvinicius@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "mysql-connector-python>=26.7.0",
]

[project.scripts]
meuprojeto = "meuprojeto:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
